config/routes.rb
Rails.application.routes.draw do
  resources :pens
  get '/',:to => "notes#index"
  get '/notes/:id', :to => "notes#show"
  post '/notes/create', :to => "notes#create"

  #get for link request
  #post for form request
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/pen.rb
class Pen < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController<ApplicationController

  def index
    @notes = Note.all
  end

  def show
    note_id = params[:id].to_i
    @current_note = Note.find (note_id)
  end

  def create
    note_content = params[:content]
    new_note = Note.new
    new_note.content = note_content
    new_note.save
    redirect_to '/'
  end
end

app/controllers/pens_controller.rb
class PensController < ApplicationController
  before_action :set_pen, only: %i[ show edit update destroy ]

  # GET /pens or /pens.json
  def index
    @pens = Pen.all
  end

  # GET /pens/1 or /pens/1.json
  def show
  end

  # GET /pens/new
  def new
    @pen = Pen.new
  end

  # GET /pens/1/edit
  def edit
  end

  # POST /pens or /pens.json
  def create
    @pen = Pen.new(pen_params)

    respond_to do |format|
      if @pen.save
        format.html { redirect_to @pen, notice: "Pen was successfully created." }
        format.json { render :show, status: :created, location: @pen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pens/1 or /pens/1.json
  def update
    respond_to do |format|
      if @pen.update(pen_params)
        format.html { redirect_to @pen, notice: "Pen was successfully updated." }
        format.json { render :show, status: :ok, location: @pen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pens/1 or /pens/1.json
  def destroy
    @pen.destroy
    respond_to do |format|
      format.html { redirect_to pens_url, notice: "Pen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pen
      @pen = Pen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pen_params
      params.require(:pen).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pens_helper.rb
module PensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test002</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/deletepage.html.erb
<%= form_tag ("/notes/delete") do %>
  <%= text_field_tag (:content) %>
  <%= submit_tag("delete") %>
<%end%>

app/views/notes/index.html.erb
<p>Notes</p>
<%= form_tag ("/notes/create") do %>
  <%= text_field_tag (:content) %>
  <%= submit_tag("create") %>
<%end%>
<ul>
  <% if @notes.size>0%>
    <% @notes.each do |note| %>
      <li><a href="/notes/<%= note.id %>">
         <%= note.content %> </a>
      </li>
    <%end%>
  <% else %>
    <p>No notes to display</p>
  <%end%>
</ul>

app/views/notes/show.html.erb
<h1><%= @current_note.content %></h1>

<p><%= @current_note.created_at %></p>

app/views/pens/_form.html.erb
<%= form_with(model: pen) do |form| %>
  <% if pen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pen.errors.count, "error") %> prohibited this pen from being saved:</h2>

      <ul>
        <% pen.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pens/edit.html.erb
<h1>Editing Pen</h1>

<%= render 'form', pen: @pen %>

<%= link_to 'Show', @pen %> |
<%= link_to 'Back', pens_path %>

app/views/pens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pens.each do |pen| %>
      <tr>
        <td><%= pen.name %></td>
        <td><%= pen.price %></td>
        <td><%= link_to 'Show', pen %></td>
        <td><%= link_to 'Edit', edit_pen_path(pen) %></td>
        <td><%= link_to 'Destroy', pen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pen', new_pen_path %>

app/views/pens/new.html.erb
<h1>New Pen</h1>

<%= render 'form', pen: @pen %>

<%= link_to 'Back', pens_path %>

app/views/pens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pen.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pen.price %>
</p>

<%= link_to 'Edit', edit_pen_path(@pen) %> |
<%= link_to 'Back', pens_path %>